channels:
- conda-forge
- nodefaults
dependencies:
- invoke
# applications
- jupyter-collaboration
# # extensions
- jupyter-offlinenotebook
- jupyterlab-fasta
- jupyterlab-geojson
# # Python Kernel
- xeus-python
- ipywidgets
- ipyleaflet
- altair
- bqplot
- dask
- matplotlib-base
- pandas
- scikit-image
- scikit-learn
- seaborn-base
- sympy
- traittypes
# C++ Kernel
# Disable the C++ kernel for now as it seems to cause mamba to not solve
# - xeus-cling
# - xtensor
# - xtensor-blas
# - xwidgets
# - xleaflet
# CLI tools
- pip
- vim